name: Whitebox Solutions
favicon: null
layout_spectrum: 0.6022531392518431
typography_spectrum: 0.8083423576317728
title: Whitebox Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#81c41d'
    - '#999999'
    - '#40841d'
    - '#c3c3c3'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
